//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSqlServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UCAInvestDBEntities : DbContext
    {
        public UCAInvestDBEntities()
            : base("name=UCAInvestDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserLocation> user_locations { get; set; }
        public virtual DbSet<UserToken> user_tokens { get; set; }
        public virtual DbSet<User> users { get; set; }
        public virtual DbSet<UserService> user_services { get; set; }
    }
}
