//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSqlServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserService
    {
        public int service_id { get; set; }
        public Nullable<int> client_user_id { get; set; }
        public Nullable<int> crane_user_id { get; set; }
        public System.Data.Entity.Spatial.DbGeography location { get; set; }
        public Nullable<long> request_timestamp { get; set; }
        public Nullable<long> taken_timestamp { get; set; }
        public Nullable<long> completed_timestamp { get; set; }
        public string description { get; set; }
    
        public virtual User ServiceUser { get; set; }
        public virtual User CraneUser { get; set; }
    }
}
